# Generated by Django 4.0.5 on 2022-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time of calculation')),
                ('principle_amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name=0)),
            ],
        ),
    ]
